---
# Author: Michael Sevilla
# Subject GassyFS to a sort

- include: site/site.yml
- include: site/check.yml
- include: site/client.yml

- hosts: client
  tasks:
    - name: get a 40MB input file
      get_url: 
        url: "http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeCaltechRnaSeq/{{ input }}"
        dest: "/tmp/input.bam"

    - name: put the input into gassyfs
      #shell: "time cp /tmp/input.bam /mount/input.bam"
      shell: "head /tmp/input.bam -c 17k > /mount/test"
      register: copy

    - name: run the sort benchmark
      shell: "time samtools sort -@ 16 -m640M -o /mount/output.bam /mount/input.bam"
      register: sort

    - debug: var=copy.stderr.split("\n")
    - debug: var=sort.stderr.split("\n")
      
