---
# Author: Michael Sevilla
# Subject GassyFS to a suite of compile workloads

- hosts: client
  tasks:
    - name: git compile and run tests
      set_fact:
        job:
          - "git clone --recursive --branch=v2.7.1 https://github.com/git/git.git /mount/git"
          - "cd git; make -j5"
          - "cd git; make test"
          - "rm -r git"

    - name: run the job 3 times
      shell: "cd /mount; {{ item }}"
      register: result
      with_items: "[{{ job }}, {{ job }}, {{ job }}]"

    - name: "parse results"
      connection: local
      template: src=workload.j2 dest=./results/output-git.csv
      with_items:
        - "{{ result.results }}"
